// Copyright 2026 Timothé Lapetite and contributors
// Released under the MIT license https://opensource.org/license/MIT/

#pragma once

#include "CoreMinimal.h"

#include "Core/PCGExAssetCollection.h"

#include "PCGExVariantCollection.generated.h"

/**
 * One override row inside a variant source group: replaces the source entry identified by
 * SourceEntryId with the entry payload held in Entry. Cross-type replacement is legal --
 * a mesh entry may be replaced by an actor entry and vice versa; consumers type-check
 * resolved entries, not their host collection.
 */
USTRUCT(BlueprintType)
struct PCGEXCOLLECTIONS_API FPCGExVariantEntryOverride
{
	GENERATED_BODY()

	/**
	 * EntryId of the source entry this row replaces (see FPCGExAssetCollectionEntry::EntryId).
	 * 0 = unbound row (never swapped). Ids are assigned on the source by SyncEntryIds during
	 * its staging rebuild -- a source that was never rebuilt has no ids to bind against.
	 */
	UPROPERTY(EditAnywhere, Category = Settings)
	int32 SourceEntryId = 0;

	/** Replacement entry. Any concrete FPCGExAssetCollectionEntry type. Unset = row inert. */
	UPROPERTY(EditAnywhere, Category = Settings, meta=(BaseStruct="/Script/PCGExCollections.PCGExAssetCollectionEntry", ExcludeBaseStruct))
	FInstancedStruct Entry;
};

/**
 * A group of overrides against one source collection, plus the baked runtime mapping.
 * BakedPairs is derived data -- regenerated by UPCGExVariantCollection::SyncVariantMappings
 * (PreSave / explicit) -- but serialized so cooked builds carry the resolved mapping.
 */
USTRUCT(BlueprintType)
struct PCGEXCOLLECTIONS_API FPCGExVariantSource
{
	GENERATED_BODY()

	/** The source collection whose picks this group can redirect. */
	UPROPERTY(EditAnywhere, Category = Settings)
	TSoftObjectPtr<UPCGExAssetCollection> Source;

	UPROPERTY(EditAnywhere, Category = Settings)
	TArray<FPCGExVariantEntryOverride> Overrides;

	/**
	 * Baked by SyncVariantMappings: X = source raw entry index, Y = this collection's raw
	 * (flattened) entry index. This is the swap hot path -- EntryIds are not consulted at runtime.
	 */
	UPROPERTY()
	TArray<FIntPoint> BakedPairs;

	/** Source stamps captured at bake time, for staleness detection. */
	UPROPERTY()
	int32 SourceNumEntriesAtBake = -1;

	/** Order-sensitive hash of the source's EntryIds in raw order -- catches same-count reorders. */
	UPROPERTY()
	uint32 SourceOrderHashAtBake = 0;

	UPROPERTY()
	uint32 SourceGUIDAtBake = 0;
};

/**
 * Authoring shorthand: "any source entry staging this asset swaps to this payload."
 * Resolves at bake time against the DECLARED sources only -- a rule with no match in any
 * source simply bakes nothing. Explicit per-entry rows always take precedence over rules.
 */
USTRUCT(BlueprintType)
struct PCGEXCOLLECTIONS_API FPCGExVariantPathOverride
{
	GENERATED_BODY()

	/** Source entries whose staged asset path (Staging.Path) equals this swap to Entry. */
	UPROPERTY(EditAnywhere, Category = Settings)
	FSoftObjectPath MatchAsset;

	/** Replacement entry. Any concrete FPCGExAssetCollectionEntry type. Unset = rule inert. */
	UPROPERTY(EditAnywhere, Category = Settings, meta=(BaseStruct="/Script/PCGExCollections.PCGExAssetCollectionEntry", ExcludeBaseStruct))
	FInstancedStruct Entry;
};

/**
 * A collection that themes other collections: per source collection, a set of override rows
 * keyed by stable EntryId, each carrying a full replacement entry of any concrete type
 * (heterogeneous by design -- mesh and actor entries can coexist).
 *
 * It is a first-class UPCGExAssetCollection: it registers with FPickPacker, resolves through
 * FPickUnpacker, and its entries carry their own staging data -- so a downstream swap node can
 * redirect pick hashes from a source's (GUID, RawIndex) to this collection's, and everything
 * downstream (spawning, fitting) keeps working off the variant entry.
 *
 * The flattened raw-index view is the concatenation of Sources[*].Overrides[*].Entry in
 * declaration order. Unset rows still consume a raw index (they are skipped by iteration and
 * cache build) so baked indices stay stable when rows are partially authored.
 */
UCLASS(BlueprintType, DisplayName="[PCGEx] Collection | Variant", meta=(ToolTip = "Per-entry overrides for one or more source collections, for end-of-pipeline asset swapping (biomes, themes)."))
class PCGEXCOLLECTIONS_API UPCGExVariantCollection : public UPCGExAssetCollection
{
	GENERATED_BODY()

public:
	virtual PCGExAssetCollection::FTypeId GetTypeId() const override
	{
		return PCGExAssetCollection::TypeIds::Variant;
	}

	/** Source collections this variant themes; overrides are grouped per source. */
	UPROPERTY(EditAnywhere, Category = Settings)
	TArray<FPCGExVariantSource> Sources;

	/**
	 * Asset-path swap rules -- shorthand over the per-entry rows. Resolved into baked pairs
	 * by SyncVariantMappings against the declared sources; entries already claimed by an
	 * explicit row are untouched (specific beats general). First matching rule wins;
	 * duplicate MatchAsset values warn at bake. Rule payloads occupy the tail of the
	 * flattened raw-index view, after all source-group rows.
	 */
	UPROPERTY(EditAnywhere, Category = Settings)
	TArray<FPCGExVariantPathOverride> PathOverrides;

	//~ UPCGExAssetCollection interface -- flattened view over Sources[*].Overrides[*].Entry.
	// InitNumEntries / Sort intentionally keep their base behavior (not-implemented / no-op):
	// entry layout is authored per-source and must not be flattened or reordered externally.
	virtual bool IsValidIndex(int32 InIndex) const override;
	virtual int32 NumEntries() const override;
	virtual void BuildCache() override;
	virtual void ForEachEntry(FForEachConstEntryFunc Iterator) const override;
	virtual void ForEachEntry(FForEachEntryFunc Iterator) override;

	/**
	 * Resolve override rows against their (loaded) sources and bake the
	 * (SourceRawIndex, VariantRawIndex) pair tables + staleness stamps.
	 * Runs on PreSave (covers manual saves AND cook saves); callable explicitly.
	 * Rows whose SourceEntryId no longer exists on the source are skipped with a warning
	 * (orphaned rows -- see plan Q2).
	 */
	void SyncVariantMappings();

	/**
	 * True if the baked mapping for the given source group no longer matches the live source
	 * (entry count, EntryId order hash, or collection GUID drifted since bake). Only meaningful
	 * when the source is loaded; unloaded sources report false (unknown).
	 */
	bool IsMappingStale(const FPCGExVariantSource& InSourceGroup) const;

	/** Find the override group for a given source collection path. Null if not themed here. */
	const FPCGExVariantSource* FindSourceGroup(const FSoftObjectPath& InSourcePath) const;

	virtual void PreSave(FObjectPreSaveContext SaveContext) override;
	virtual void PostLoad() override;

#if WITH_EDITOR
	virtual void PostEditChangeProperty(FPropertyChangedEvent& PropertyChangedEvent) override;
#endif

protected:
	virtual const FPCGExAssetCollectionEntry* GetEntryAtRawIndex(int32 Index) const override;
	virtual FPCGExAssetCollectionEntry* GetMutableEntryAtRawIndex(int32 Index) override;

	/** Flat raw index -> row payload. O(log groups) via the cached offsets when built. */
	FPCGExAssetCollectionEntry* ResolveRawIndex(int32 Index);
	const FPCGExAssetCollectionEntry* ResolveRawIndex(int32 Index) const;

	/** Flat raw index -> the row's payload. Sole owner of the flat-index traversal, so the entry
	 *  pointer and its type can't disagree. */
	const FInstancedStruct* ResolveRawPayload(int32 Index) const;

#if WITH_EDITOR
public:
	/** Rows carry their own payload type; the base `Entries` reflection finds nothing here. */
	virtual const UScriptStruct* EDITOR_GetEntryScriptStruct(int32 RawIndex) const override;

protected:
#endif

	/**
	 * Cached flat-view structure: FlatGroupOffsets[g] = flat start index of Sources[g]'s rows,
	 * with one trailing element = start of the PathOverrides payload tail. FlatTotalEntries < 0
	 * means "not built yet" (fresh object) and lookups fall back to a linear walk.
	 *
	 * CONTRACT: rebuilt on PostLoad / PostEditChangeProperty / SyncVariantMappings -- any code
	 * that mutates Sources or PathOverrides structurally OUTSIDE those notification paths must
	 * call RebuildFlatView() itself. Assets are structurally immutable during PCG execution,
	 * which is what makes the unguarded hot-path read safe.
	 */
	TArray<int32> FlatGroupOffsets;
	int32 FlatTotalEntries = INDEX_NONE;

	void RebuildFlatView();
};
